export const allCollaboratorsData = [
    {
        "Expiration date": "10/10/2026",
        "Name": "Boeno, Eric G.",
        "Certified Company": "YM",
        "Certified Dept": "PPC YM",
        "Issue number": "6400-5",
        "Type": "TECHNICAL (TC)",
        "Process": "BL-A, EC-A",
        "Process Code Definition": "BL-A BALANCE EXCEL-ATO, EC-A EST. CAPACIDADE-ATO",
        "Imagem": "profile.jpg",
        "Local": "Tatuí, SP, Brasil"
    },
    {
        "Expiration date": "21/07/2026",
        "Name": "De Silva Lima, Agatha I.",
        "Certified Company": "YBL-B",
        "Certified Dept": "MANUF ENG",
        "Issue number": "",
        "Type": "TECHNICAL (TC)",
        "Process": "BL-A, EC-A",
        "Process Code Definition": "BL-A BALANCE EXCEL-ATO, EC-A EST. CAPACIDADE-ATO",
        "Imagem": "Agatha Isabele Da Silva Lima.jpg",
        "Local": "Bonito, PE, Brasil"
    },
    {
        "Expiration date": "21/07/2026",
        "Name": "Castelló Rodriguez, Diana C.",
        "Certified Company": "YAS",
        "Certified Dept": "MANUF ENG",
        "Issue number": "1139",
        "Type": "TECHNICAL (TC)",
        "Process": "BL-A, EC-A",
        "Process Code Definition": "BL-A BALANCE EXCEL-ATO, EC-A EST. CAPACIDADE-ATO",
        "Imagem": "",
        "Local": "Escobar, CT, Argentina"
    },
    {
        "Expiration date": "21/07/2026",
        "Name": "Barros, Mara L.",
        "Certified Company": "YAS",
        "Certified Dept": "MANUF ENG",
        "Issue number": "3089",
        "Type": "TECHNICAL (TC)",
        "Process": "BL-A, EC-A",
        "Process Code Definition": "BL-A BALANCE EXCEL-ATO, EC-A EST. CAPACIDADE-ATO",
        "Imagem": "",
        "Local": "Escobar, CT, Argentina"
    },
    {
        "Expiration date": "21/07/2026",
        "Name": "Farias, José L.",
        "Certified Company": "YAS",
        "Certified Dept": "MANUF ENG",
        "Issue number": "028",
        "Type": "TECHNICAL (TC)",
        "Process": "BL-A, EC-A",
        "Process Code Definition": "BL-A BALANCE EXCEL-ATO, EC-A EST. CAPACIDADE-ATO",
        "Imagem": "",
        "Local": "Escobar, CT, Argentina"
    },
    {
        "Expiration date": "21/07/2026",
        "Name": "Redondo, Franco N.",
        "Certified Company": "YAS",
        "Certified Dept": "MANUF ENG",
        "Issue number": "299",
        "Type": "TECHNICAL (TC)",
        "Process": "BL-A, EC-A",
        "Process Code Definition": "BL-A BALANCE EXCEL-ATO, EC-A EST. CAPACIDADE-ATO",
        "Imagem": "",
        "Local": "Escobar, CT, Argentina"
    },
    {
        "Expiration date": "21/07/2026",
        "Name": "Silva, Jonathan R.",
        "Certified Company": "YBM",
        "Certified Dept": "MANUF ENG",
        "Issue number": "5408-0",
        "Type": "TECHNICAL (TC)",
        "Process": "BL-A, EC-A",
        "Process Code Definition": "BL-A BALANCE EXCEL-ATO, EC-A EST. CAPACIDADE-ATO",
        "Imagem": "Jonathan Rafael Silva.jpg",
        "Local": "Matozinhos, MG, Brasil"
    },
    {
        "Expiration date": "21/07/2026",
        "Name": "De Lima, Raphael C.",
        "Certified Company": "YBM",
        "Certified Dept": "MANUF ENG",
        "Issue number": "323-0",
        "Type": "TECHNICAL (TC)",
        "Process": "BL-A, EC-A",
        "Process Code Definition": "BL-A BALANCE EXCEL-ATO, EC-A EST. CAPACIDADE-ATO",
        "Imagem": "",
        "Local": "Matozinhos, MG, Brasil"
    },
    {
        "Expiration date": "21/07/2026",
        "Name": "Ribeiro, Paola.",
        "Certified Company": "YBL-T",
        "Certified Dept": "MANUF ENG",
        "Issue number": "6462-5",
        "Type": "TECHNICAL (TC)",
        "Process": "BL-A, EC-A",
        "Process Code Definition": "BL-A BALANCE EXCEL-ATO, EC-A EST. CAPACIDADE-ATO",
        "Imagem": "",
        "Local": "Tatuí, SP, Brasil"
    },
    {
        "Expiration date": "21/07/2026",
        "Name": "Mariano, Gessica C.",
        "Certified Company": "YBL-T",
        "Certified Dept": "MANUF ENG",
        "Issue number": "6183-9",
        "Type": "TECHNICAL (TC)",
        "Process": "BL-A, EC-A",
        "Process Code Definition": "BL-A BALANCE EXCEL-ATO, EC-A EST. CAPACIDADE-ATO",
        "Imagem": "",
        "Local": "Tatuí, SP, Brasil"
    },
    {
        "Expiration date": "21/07/2026",
        "Name": "Cappelletti, Tiago T.",
        "Certified Company": "YBL-I",
        "Certified Dept": "MANUF ENG",
        "Issue number": "",
        "Type": "TECHNICAL (TC)",
        "Process": "BL-A, EC-A",
        "Process Code Definition": "BL-A BALANCE EXCEL-ATO, EC-A EST. CAPACIDADE-ATO",
        "Imagem": "",
        "Local": "Irati, PR, Brasil"
    }
];